Repository gbowne1/spmssite, pull requests merged in 2022-08, with the labels that each got.

#44 fixed issue #42
  images/favicon.png
  images/logo.jpg
  index.html
  styles.css
Labels: bug, enhancement, help wanted, good first issue

#54 This commit includes changes for docs and adds rfq
  .github/PULL_REQUEST_TEMPLATE.yml
  .vscode/settings.json
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  SUPPORT.md
  jobs.html
  rfq.html
Labels: bug, documentation, enhancement

#61 Add light/dark mode toggle in about.html
  src/css/styles.css
  templates/about.html
Labels: help wanted, good first issue

#70 Fix/reformat jobs page
  .DS_Store
  src/css/jobsStyles.css
  templates/applicationReceived.html
  templates/jobs.html
Labels: enhancement, help wanted, good first issue

#77 Fix contact page
  src/css/styles.css
  templates/contact.html
Labels: bug, enhancement, help wanted
