Repository gbowne1/spmssite, pull requests merged in 2022-09, with the labels that each got.

#101 This PR moves these changes back to main.
  src/css/styles.css
  templates/about.html
  templates/index.html
  templates/rfq.html
Labels: bug

#105 Major changes to these files
  .vscode/settings.json
  src/css/styles.css
  src/images/logo.jpg
  src/js/contact.js
  src/js/cookieConsent.js
  src/js/myModal.js
  templates/about.html
  templates/capabilities.html
  templates/contact.html
  templates/index.html
  templates/privacy.html
  templates/rfq.html
  templates/terms.html
Labels: bug, documentation, enhancement, help wanted, good first issue, question

#113 Changed In about.html and src\css\styles.css
  src/css/styles.css
  templates/about.html
Labels: enhancement, good first issue

#117 Changes In DarkMode Section, added a new carousel slider
  src/css/styles.css
  src/images/facilities1.jpg
  src/images/facilities2.jpg
  src/images/facilities3.jpg
  templates/about.html
Labels: bug, enhancement, help wanted
